name: Windows .NET Self-Contained EXE

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore
      run: dotnet restore SDUDPMEUHMEPTQILSPX/SDUDPMEUHMEPTQILSPX.csproj -r win-x64

    - name: Build
      run: dotnet build SDUDPMEUHMEPTQILSPX/SDUDPMEUHMEPTQILSPX.csproj --no-restore -c Release -r win-x64

    - name: Publish
      run: dotnet publish SDUDPMEUHMEPTQILSPX/SDUDPMEUHMEPTQILSPX.csproj -c Release -r win-x64 --self-contained true `
        /p:PublishSingleFile=true `
        /p:IncludeAllContentForSelfExtract=true `
        /p:EnableCompressionInSingleFile=true `
        --output ./publish


    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-wpf-app
        path: ./publish/
